server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  signerKey: "bb4ffa41d35cecca49e1f773e25c2e57eae9b458aeed128181be1ad96bbc56e1"
  valid-duration: 20
  refreshable-duration: 120